config/routes.rb
Rails.application.routes.draw do
  get 'raffle/index'

  resources :raffle
  resources :scholarships
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users

  get 'static_pages/instructions'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/landing_page'

  root 'static_pages#landing_page'

end

app/models/scholarship.rb
class Scholarship < ActiveRecord::Base
	belongs_to :user

	#User must fully fill out all forms application
	validates :name, presence: true
	validates :gender, presence: true
	validates :date_of_birth, presence: true
	validates :gpa, presence: true
	validates :university, presence: true
	validates :address, presence: true
	validates :state, presence: true
 end

app/controllers/scholarships_controller.rb
class ScholarshipsController < ApplicationController
  #Users who are not signed in cannot view scholarship
  before_action :authenticate_user!
  before_action :set_scholarship, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  before_action :check_scholarship, only: %i[new create]

  def index
    @scholarships = Scholarship.all
  end

  def show
  end

  def show_current_user_scholarship
    @user = User.find(params[:id])
    @scholarships = Scholarship.where(user_id: @user.id)
  end

  def new
    @scholarship = Scholarship.new
  end

  def edit
  end

  def create
    @scholarship = Scholarship.new(scholarship_params)
    @scholarship.user_id = current_user.id
    @scholarship.id = current_user.scholarship_id

    respond_to do |format|
      if @scholarship.save
        format.html { redirect_to @scholarship, notice: 'Scholarship was successfully created.' }
        format.json { render :show, status: :created, location: @scholarship }
      else
        format.html { render :new }
        format.json { render json: @scholarship.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @scholarship.update(scholarship_params)
        format.html { redirect_to @scholarship, notice: 'Scholarship was successfully updated.' }
        format.json { render :show, status: :ok, location: @scholarship }
      else
        format.html { render :edit }
        format.json { render json: @scholarship.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @scholarship.destroy
    respond_to do |format|
      format.html { redirect_to scholarships_url, notice: 'Scholarship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scholarship
      @scholarship = Scholarship.find(params[:id])
    end

    def check_scholarship
        if current_user.scholarship.present?
            redirect_to root_url
        end
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def scholarship_params
      params.require(:scholarship).permit(:name, :gender, :date_of_birth, :gpa, :address, :state, :university, :essay, :user_id)
    end
end

app/helpers/scholarships_helper.rb
module ScholarshipsHelper
end

app/views/scholarships/_current_user_scholarship.html.erb
<% if user_signed_in? && current_user.role == "User" %>

<h1 class="center">Your Scholarship</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Date of birth</th>
      <th>GPA</th>
      <th>Address</th>
      <th>State</th>
      <th>University</th>
      <th>Essay</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= current_user.scholarship %></td>
        <td><%= current_user.scholarship.name %></td>
        <td><%= current_user.scholarship.gender %></td>
        <td><%= current_user.scholarship.date_of_birth %></td>
        <td><%= current_user.scholarship.gpa %></td>
        <td><%= current_user.scholarship.address %></td>
        <td><%= current_user.scholarship.state %></td>
        <td><%= current_user.scholarship.university %></td>
        <td><%= current_user.scholarship.essay %></td>
        <td><%= link_to 'Show', current_user.scholarship %></td>
        <td><%= link_to 'Edit', current_user.edit_scholarship_path(scholarship) %></td>
        <td><%= link_to 'Destroy', current_user.scholarship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  </tbody>
</table>

<% end %>

app/views/scholarships/_form.html.erb
<%= form_for(@scholarship) do |f| %>
  <% if @scholarship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scholarship.errors.count, "error") %> prohibited this scholarship from being saved:</h2>

      <ul>
      <% @scholarship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.radio_button :gender, 'Male' %>Male<br>
    <%= f.radio_button :gender, 'Female' %>Female
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br>
    <%= f.date_select :date_of_birth, :start_year => 1940, :end_year => 2016 %>
  </div>
  <div class="field">
    <%= f.label :gpa, 'GPA' %><br>
    <%= f.select :gpa, ['1.0-2.5', '2.5-3.0', '3.0-3.5', '3.5-4.0', '4.0 and Above']%>
  </div>
    <div class="field">
    <%= f.label :address, 'Home Address' %><br>
    <%= f.text_field :address%>
  </div>
    <div class="field">
    <%= f.label :state, 'State' %><br>
    <%= f.text_field :state, :id => "state-field", :onkeydown=>"updateStateSearch()" %>
  </div>
  <div class="field">
    <%= f.label :university, "Intended Institution"%><br>
    <%= f.text_field :university, :id => "uni-field", :onkeydown=> "updateUniSearch()"%>
  </div>
  <div class="field">
    <%= f.label :essay, 'Essay (1000 character limit)' %><br>
    <p id="char-limit"></p>
    <%= f.text_area :essay, :id => "essay-form", :onkeydown=>"updateCounter()", :limit => 1000 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scholarships/_show_all_user_scholarships.html.erb
<% if user_signed_in? && current_user.role == "Admin" %>

<h1 class="center">All User Scholarships</h1>

<table class="table">
  <thead>
    <tr>
      <th>User ID</th>
      <th>Name</th>
      <th>Gender</th>
      <th>Date of birth</th>
      <th>State</th>
      <th>University</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scholarships.each do |scholarship| %>
      <tr>
        <td><%= scholarship.user_id %></td>
        <td><%= scholarship.name %></td>
        <td><%= scholarship.gender %></td>
        <td><%= scholarship.date_of_birth %></td>
        <td><%= scholarship.state %></td>
        <td><%= scholarship.university %></td>
        <td><%= link_to 'Show', scholarship, class: "btn btn-success", style: "color:white" %></td>
        <td><%= link_to 'Edit', edit_scholarship_path(scholarship), class: "btn btn-warning", style: "color:white" %></td>
        <td><%= link_to 'Destroy', scholarship, method: :delete, data: { confirm: 'Are you sure you wish to delete this scholarship? This cannot be undone.' }, class: "btn btn-danger", style: "color:white" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/scholarships/_show_current_user_scholarship.html.erb
<% if user_signed_in? && current_user.role == "User" %>

<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Date of birth</th>
      <th>State</th>
      <th>University</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= current_user.scholarship.name %></td>
        <td><%= current_user.scholarship.gender %></td>
        <td><%= current_user.scholarship.date_of_birth %></td>
        <td><%= current_user.scholarship.state %></td>
        <td><%= current_user.scholarship.university %></td>
        <td><%= link_to 'Show', current_user.scholarship, class: "btn btn-success", style: "color:white" %></td>
        <td><%= link_to 'Edit', edit_scholarship_path(current_user.scholarship), class: "btn btn-warning", style: "color:white" %></td>
        <td><%= link_to 'Destroy', current_user.scholarship, method: :delete, data: { confirm: 'Are you sure you wish to delete this scholarship? This cannot be undone.' }, class: "btn btn-danger", style: "color:white" %></td>
      </tr>
  </tbody>
</table>


<% end %>

app/views/scholarships/edit.html.erb
<h1>Editing Scholarship</h1>

<%= render 'form' %>

<%= link_to 'Show', @scholarship %> |
<%= link_to 'Back', scholarships_path %>

app/views/scholarships/index.html.erb
<p id="notice"><%= notice %></p>

<% if user_signed_in? && current_user.role == "Admin" %>

  <%= render partial: 'show_all_user_scholarships' %>


  <%= link_to 'New Scholarship', new_scholarship_path, class: "btn btn-primary", style: "color:white" %>

<% elsif user_signed_in? && current_user.role == "User"  && current_user.scholarship.nil?%>

  <p class="center">It appears that you do not have a scholarship on file with us. Click below to get started!</p>

  <%= link_to 'New Scholarship', new_scholarship_path, class: "btn btn-primary", style: "color:white" %>

  <% elsif user_signed_in? && current_user.role == "User" %>

  <%= render partial: 'show_current_user_scholarship' %>

<% end %>

<br>

app/views/scholarships/new.html.erb
<h1>New Scholarship</h1>

<%= render 'form' %>

<%= link_to 'Back', scholarships_path %>

app/views/scholarships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Scholarship ID:</strong>
  <%= @scholarship.id %>
</p>

<p>
  <strong>User ID:</strong>
  <%= @scholarship.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @scholarship.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @scholarship.gender %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @scholarship.date_of_birth %>
</p>

<p>
  <strong>GPA:</strong>
  <%= @scholarship.gpa %>
</p>

<p>
  <strong>Address:</strong>
  <%= @scholarship.address %>
</p>

<p>
  <strong>State:</strong>
  <%= @scholarship.state %>
</p>

<p>
  <strong>University:</strong>
  <%= @scholarship.university %>
</p>

<p>
  <strong>Essay:</strong>
  <%= @scholarship.essay %>
</p>

<%= link_to 'Edit', edit_scholarship_path(@scholarship) %> |
<%= link_to 'Back', scholarships_path %>